version: 2
jobs:
  deploy_to_gallery:
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/dash-sample-apps
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: |
            echo "export DASH_ENTERPRISE_USERNAME=$GALLERY_DEPLOY_USERNAME" >> $BASH_ENV
            echo "export DASH_ENTERPRISE_PASSWORD=$GALLERY_DEPLOY_PASSWORD" >> $BASH_ENV
            echo "export DASH_ENTERPRISE_URL=$DASH_GALLERY_ENTERPRISE_URL" >> $BASH_ENV
            echo "export DASH_ENTERPRISE_API_KEY=$DASH_GALLERY_ENTERPRISE_API_KEY" >> $BASH_ENV
            echo "export APP=dash-world-cell-towers" >> $BASH_ENV
            echo "export DDS_CLIENT_VERSION=0.1.0" >> $BASH_ENV
            echo "export LLVM_CONFIG=/usr/bin/llvm-config-8" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set up git config
          command: |
            printf '#!/bin/bash\necho username=$DASH_ENTERPRISE_USERNAME\necho password=$DASH_ENTERPRISE_PASSWORD' >> /home/circleci/helper-script.sh
            git remote add plotly $DASH_ENTERPRISE_URL/GIT/$APP
            git config --global credential.helper "/bin/bash /home/circleci/helper-script.sh"
            git config --global user.email '<>' # Leave email blank
            git config --global user.name "Circle MonoRepo Automatic Deployer"
      - run:
          name: Install dds-client
          command: |
            curl -sSL -o dds-client.tgz "https://github.com/plotly/dds-client/releases/download/v${DDS_CLIENT_VERSION}/dds-client_${DDS_CLIENT_VERSION}_linux_x86_64.tgz"
            mkdir $HOME/bin
            tar xzf dds-client.tgz -C $HOME/bin
            chmod +x $HOME/bin/dds-client
      - run:
          name: Deploy
          command: |
            if ! dds-client apps:exists --name "$APP" >/dev/null 2>&1; then
              dds-client apps:create --name "$APP"
            fi

            git push plotly master
  deploy_to_sales:
    docker:
      - image: circleci/python:3.6-stretch
    working_directory: ~/dash-sample-apps
    steps:
      - checkout
      - run:
          name: Setup custom environment variables
          command: |
            echo "export DASH_ENTERPRISE_USERNAME=$SALES_DEPLOY_USERNAME" >> $BASH_ENV
            echo "export DASH_ENTERPRISE_PASSWORD=$SALES_DEPLOY_PASSWORD" >> $BASH_ENV
            echo "export DASH_ENTERPRISE_URL=$DASH_SALES_ENTERPRISE_URL" >> $BASH_ENV
            echo "export DASH_ENTERPRISE_API_KEY=$DASH_SALES_ENTERPRISE_API_KEY" >> $BASH_ENV
            echo "export APP=dash-world-cell-towers" >> $BASH_ENV
            echo "export DDS_CLIENT_VERSION=0.1.0" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set up git config
          command: |
            printf '#!/bin/bash\necho username=$DASH_ENTERPRISE_USERNAME\necho password=$DASH_ENTERPRISE_PASSWORD' >> /home/circleci/helper-script.sh
            git remote add plotly $DASH_ENTERPRISE_URL/GIT/$APP
            git config --global credential.helper "/bin/bash /home/circleci/helper-script.sh"
            git config --global user.email '<>' # Leave email blank
            git config --global user.name "Circle MonoRepo Automatic Deployer"
      - run:
          name: Install dds-client
          command: |
            curl -sSL -o dds-client.tgz "https://github.com/plotly/dds-client/releases/download/v${DDS_CLIENT_VERSION}/dds-client_${DDS_CLIENT_VERSION}_linux_x86_64.tgz"
            mkdir $HOME/bin
            tar xzf dds-client.tgz -C $HOME/bin
            chmod +x $HOME/bin/dds-client
      - run:
          name: Deploy
          command: |
            if ! dds-client apps:exists --name "$APP" >/dev/null 2>&1; then
              dds-client apps:create --name "$APP"
            fi

            git push plotly master

workflows:
  version: 2
  build:
    jobs:
      - deploy_to_gallery:
          filters:
            branches:
              only:
              - master
      - deploy_to_sales:
          filters:
            branches:
              only:
              - master
