theme = {
    "dark": {
        "accent": "#978bf2",
        "accent_negative": "#ff2c6d",
        "accent_positive": "#00f2e4",
        "background_content": "#131416",
        "background_page": "black",
        "body_text": "#FCFDFE",
        "border": "#282D33",
        "breakpoint_font": "1200px",
        "breakpoint_stack_blocks": "700px",
        "card_background_color": "#141517",
        "card_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
        "card_margin": "7px",
        "card_padding": "0px",
        "card_outline": {"width": "0px", "style": "solid", "color": "#282D33"},
        "card_header_border": {
            "width": "0px",
            "style": "solid",
            "color": "#282D33",
            "radius": "0px",
        },
        "card_header_background_color": "#131416",
        "card_header_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
        "card_header_margin": "0px",
        "card_header_padding": "10px",
        "colorway": [
            "#978bf2",
            "#ff2c6d",
            "#ff7f0e",
            "#2ca02c",
            "#d62728",
            "#8c564b",
            "#e377c2",
            "#7f7f7f",
            "#bcbd22",
            "#17becf",
        ],
        "colorscale": ["#978bf2", "#060606", "#ff2c6d"],
        "font_family": "Open Sans",
        "font_size": "22px",
        "font_size_smaller_screen": "13px",
        "font_family_header": "Open Sans",
        "font_size_header": "18px",
        "font_family_headings": "Open Sans",
        "font_headings_size": "null",
        "header_border": {
            "width": "0px",
            "style": "solid",
            "color": "#282D33",
            "radius": "0px",
        },
        "header_background_color": "black",
        "header_box_shadow": "none",
        "title_capitalization": "capitalize",
        "header_content_alignment": "spread",
        "header_margin": "0px 0px 15px 0px",
        "header_padding": "0px",
        "header_text": "white",
        "heading_text": "white",
        "text": "#A2AAB8",
        "report_font_family": "Open Sans",
        "report_font_size": "12px",
        "report_background_page": "white",
        "report_background_content": "#FAFBFC",
        "report_text": "black",
    },
}
